GET http://localhost:8000/produto/0 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/4 HTTP/1.1
content-type: application/json

{
    "nome" : "Abc da Silva",
    "descricao" : "toppp",
    "telefone" : "49988234567",
    "foto" : "image.png",
    "valor_unitario" : 1
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Abc da Silva",
    "descricao" : "toppp",
    "telefone" : "49988234567",
    "foto" : "image.png",
    "valor_unitario" : 2
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1