### Verbo GET – listar
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
### Verbo GET – listar todos
curl -X 'GET' \
'http://localhost:8000/funcionario/' \
-H 'accept: application/json' \
-H 'x-token: abcBolinhasToken' \
-H 'x-key: abcBolinhasKey2'


### Verbo POST - adicionar
POST http://localhost:8000/funcionario/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type : application/json

{
    "nome" : "Lucas Vieira",
    "matricula" : "123",
    "cpf" : "35425252",
    "telefone" : "5235252",
    "grupo" : 1,
    "senha" : "bolinhas1"
}

### Verbo PUT - atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type : application/json

{
    "nome" : "Topserson da Silva" ,
    "matricula" : "54321" ,
    "cpf" : "325252" ,
    "telefone" : "53252352" ,
    "grupo" : 2 ,
    "senha" : "abc"
}

### Verbo DELETE - atualiza
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type : application/json